# Generated by Django 2.2.5 on 2020-02-13 09:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='サイト名')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('comment', models.CharField(max_length=100, verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blackurl',
            },
        ),
    ]
